In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('Name.csv')

In [4]:
data

Weight  Height
0       56    1.60
1       66    1.45
2       77    1.44
3       56    1.50
4       34    1.07
5       56    1.63
6       23    1.22
7       45    1.35
8       23    1.33
9       89    1.07
10     104    1.45
11      34    1.02
12      58    1.00
13      65    1.60
14      76    1.59
15      59    1.58
16      95    1.57
17      98    1.55
18      89    1.45
19      34    1.44

In [5]:
X=data.Weight.values

In [6]:
X

array([ 56,  66,  77,  56,  34,  56,  23,  45,  23,  89, 104,  34,  58,
        65,  76,  59,  95,  98,  89,  34], dtype=int64)

In [6]:
X=X.reshape(-1,1)

In [13]:
X

array([[ 56],
       [ 66],
       [ 77],
       [ 56],
       [ 34],
       [ 56],
       [ 23],
       [ 45],
       [ 23],
       [ 89],
       [104],
       [ 34],
       [ 58],
       [ 65],
       [ 76],
       [ 59],
       [ 95],
       [ 98],
       [ 89],
       [ 34]], dtype=int64)

In [14]:
y=data.Height.values

In [15]:
y # original output - target

array([1.6 , 1.45, 1.44, 1.5 , 1.07, 1.63, 1.22, 1.35, 1.33, 1.07, 1.45,
       1.02, 1.  , 1.6 , 1.59, 1.58, 1.57, 1.55, 1.45, 1.44])

In [9]:
rgr=LinearRegression() # linear regression algorithm invocation

In [11]:
model=rgr.fit(X,y)

In [16]:
ypre=model.predict(X)
print(ypre) # predicted output - target - yhat

[1.37734331 1.40838038 1.44252116 1.37734331 1.30906176 1.37734331
 1.27492099 1.34320254 1.27492099 1.47976564 1.52632124 1.30906176
 1.38355073 1.40527668 1.43941745 1.38665444 1.49838788 1.507699
 1.47976564 1.30906176]


In [19]:
mse=mean_squared_error(y,ypre)
mse

0.03603826512084459

In [20]:
rmse=np.sqrt(mse)

In [21]:
score=rgr.score(X,y)

In [22]:
print("Root Mean Square Value is: ",rmse)

Root Mean Square Value is:  0.18983747027614067


In [23]:
print("error value is : ",score)

error value is :  0.13690621735623876


In [24]:
print('training time accuracy',(100-score*100),'%')
print('testing time accuracy',(100-rmse*100),'%')

training time accuracy 86.30937826437612 %
testing time accuracy 81.01625297238593 %


In [20]:
# over fitting - low bias high variance 

In [ ]:
# machine learning - steps to predict
#------------------------------------------------
# 1. importation of sklearn and necessary modules
# 2. import and read the necessary input dataset
# 3. provide x(input value) and y(target value)
# 4. preprocess the input value x if needed
# 5. invoke the algorithm imported
# 6. create model and fit the input credentials x,y to the model
# 7. predict the output using model (ypre)
# 8. use metrics to display the predicted output